sudo: required

language: go

go:
  - 1.5.1

services:
  - docker

before_install:
  - docker-compose -f ./streams/docker-compose.yml up -d roshi

install:
  - make setup-ci

script: make test

notifications:
  slack: ***REMOVED***

cache:
  directories:
    - streams/vendor
