sudo: required
language: go
go:
- 1.5.1
services:
- docker
env:
  global:
  - GO15VENDOREXPERIMENT=1
before_install:
- docker-compose up -d roshi
install:
- make setup
script:
- make test
notifications:
  email: false
  slack:
    on_success: change
    on_failure: change
    rooms:
      secure: hOuHR3RA260JlVLj1jFiXT0fP6lthG58U4HQoiNSAdsilzLYlT6/1JPikQLIBIKJBSsTtZxdMSNZLwuixPpQLGHJJLZ1g70A1xNZK1mZ20ofeYKyHviyDWcsSTeCYUhMtnkm7XnEM9EJCaB8w2n5e2B61QeMZf57R3sYoC1GS+rAkqvgMgVlqlpAV3Pq1eo4zEY30LJo0Nmaz5IQzS+QN3a9hshftPKaBR9eNjpuIvYJNXjUMRsJZCjVh70pvM1b/Mqwrl4hoc8gEa1Ec9+ESr+VEz4gzlXY4Be7CiMvzyW8oAg8CAEluLUMulN0daXUsN2fWkvpSgjbDwZsrpnMencgZuDsyoNTfPg/5LzA9WHaBgnJAtC25BG7a/RTW6/GyEdLjJxT4DlEwpaRDMSaYqqgE3Vml8cGBVyzSHPd0lT0Jog0LdQ72+T8P3bu3j7UIEkbkq4Z4mHj4XaOI3r9UU2GSM8lJJr0GuSNiUOZ/qniMcjCvsNduW7x9HW9VVy8o1QNeGjys9BpJpA90Y/BRZicEcV3uHHJeyGmz6rYmij3JsNBkmw253D5pYEA3fAmH11g6JtJqwPcg/TlkAOQ37nEEgUIp++VEQOPJw83yI5Emy4BKigMf11uS52XVBHdc1q/dTF4ypda4LNBq1KwbD19RcL8MOAE6667UtewVQM=
